### ISSUE TITLE
Pretrained models link (GoogleDrive) not accessible.

### ISSUE THREAD

**Issue by kjerk** [wwlCape/HAN#1]
Hello! Thank you for taking the time to upload your work.

I was hoping to test your model's results without starting from scratch but the google drive link for the pretrained weights seems to require approved access instead of being open.

**Comment by pearlie317** [comment]
the same here. hope you can share again! Thanks!

**Comment by Jee-King** [comment]
Hi,

Can you provide a link that contains the Super-Resolved images (of different scales) from the benchmark datasets? Like a zip file or something similar?

**Comment by GuideWsp** [comment]
+1

**Comment by TheoGreenslade** [comment]
Hi! I was hoping to use these pre-trained weights too. Did anyone manage to get access? Thank you for your help!

**Comment by kjerk** [comment]
An update for those maybe still watching this issue, it seems the author has fixed the google drive link and the weights are now available.
Thanks @wwlCape !
