### ISSUE TITLE
PSNR is not updating during training

### ISSUE THREAD

**Issue by aatiqa-ghazali** [wwlCape/HAN#10]
![Screenshot 2021-10-25 124543](https://user-images.githubusercontent.com/64826337/138655267-bd9dc69f-d558-4a97-97af-de20ec9311c5.png)

During training for scale x4 PSNR value is not updating same is the case with scale 2 and others.
Can someone guide me in this regard that what mistake I am doing?

**Comment by aatiqa-ghazali** [comment]
solved!

**Comment by 761qgmpgz943** [comment]
> solved!

how did you solve this problem，I also meet the same problem when i train RCAN
